import Head from 'next/head'

export default function Home() {
  return (
    <div>
      <Head>
        <title>facebook - meta - 22</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <h1 className='text-xs'>Building facebook</h1>
      
    </div>
  )
}
