import Head from 'next/head'
import Header from '../components/Header'
import { getSession } from "next-auth/react"
import Login from '../components/Login'
import SideBar from '../components/SideBar'

export default function Home({session}) {
  if(!session) {
    return <Login/>
  }
  return (
    <div>
      <Head>
        <title>facebook - meta - 22</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {/* Header */}
      <Header/>

      <main>
        {/* SIDEBAR */}
        <SideBar/>
        {/* FEED */}
        {/* WIDGETS */}
      </main>

    </div>
  )
}

export async function getServerSideProps(context) {
  const session = await getSession(context);
  console.log('session', session)

  return { 
    props: {session}
  }
}